# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  build:  
    # Declare a dependency on the cirrusci/flutter docker image
    docker:
      - image: cirrusci/flutter:v1.5.8 
    
    # Flutter channel to run with
    branches:
      only: master

    # Run the job in its own container with different tasks as setps
    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk 

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk